### ISSUE TITLE
Cursor blink not respecting theme background

### ISSUE THREAD

**Issue by Daeraxa** [Spiker985/x-terminal-reloaded#39]
If you set the theme to `One Dark` (only an example but this happens with basically all themes) you will notice that it displays a block cursor that alternates between `#528bff` and `#000000`. The issue is that the background for `One Dark` should be `#282c34` (https://github.com/Spiker985/x-terminal-reloaded/blob/ba3a2e0aeb7d5da21377d55a2ab08175f21749ea/src/element.js#L350). Basically the "off" state of the cursor *should* be respecting the background colour of the terminal theme but is instead always defaulting to black.

**Comment by Spiker985** [comment]
So, the reason it doesn't do that appears to be because `colors.cursorAccent` isn't set - so it is defaulting back to the original color within `src/config.js`

Adding `colors.cursorAccent = '#282c34'` to line 353 seems to solve this problem

So, I simply need to add cursorAccent lines matching the background
