### ISSUE TITLE
Font restyling

### ISSUE THREAD

**Issue by NIGHTWAV3** [Spiker985/x-terminal-reloaded#44]
Hi Spiker! Is there any way that the package can be refactored to support terminal font restyling, including non-monospace fonts (I'm specifically looking for Linux Biolinum O font). If it is possible, please let me know how I can help. Thanks!

**Comment by Spiker985** [comment]
By default it pulls from your Pulsar's default Font Family, found under Settings -> Editor -> Font Family.

However, you can also change this under the package settings. Make sure you uncheck "Use editor's Font Family", otherwise it will continue to use your default editor font

![image](https://user-images.githubusercontent.com/7829451/234009923-2f618a39-0d25-460b-8c99-a0122282d34b.png)
